apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-monitor

resources:
- github.com/redhat-cop/gitops-catalog/grafana-operator/overlays/user-app

# Patch in namespace for Argo CD that is managing this namespace
patches:
- patch: |-
    - op: add
      path: /spec/config/users
      value:
        default_theme: light
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
    - op: replace
      path: /spec/containers/0/env/0/value
      value: '-openshift-sar={"namespace":"product-catalog-monitor","resource":"routes","name":"grafana-route","verb":"get"}'
    - op: add
      path: /spec/containers/0/ports/0/protocol
      value: TCP
    - op: replace
      path: /apiVersion
      value: grafana.integreatly.org/v1beta1
  target:
    kind: Grafana
    name: grafana
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
    - op: replace
      path: /apiVersion
      value: grafana.integreatly.org/v1beta1
  target:
    kind: GrafanaDataSource
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: product-catalog-monitor
    - op: replace
      path: /metadata/name
      value: cluster-monitoring-view-product-catalog-monitor
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cluster-monitoring-view
