apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    alertmanagerMain:
      enableUserAlertmanagerConfig: true
    prometheusK8s:
      externalLabels:
        cluster: ${CLUSTER_GITOPS_NAME}
      volumeClaimTemplate:
       spec:
         accessModes:
         - ReadWriteOnce
         volumeMode: Filesystem
         resources:
           requests:
             storage: 40Gi
